# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-27 16:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_channels_in_group_channel_split'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channels_in_group',
            old_name='channel_split',
            new_name='channel_split_budget',
        ),
        migrations.AddField(
            model_name='channels_in_group',
            name='channel_split_views',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
